// components/sections/Projetos.tsx
"use client";

import React, { useState } from 'react';
import { projetos } from '@/data/ProjetosData';

type Project = (typeof projetos)[number];

export default function Projetos() {
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);

  return (
    <div className="projects-section">
      <h2 className="text-3xl md:text-4xl font-bold text-center mb-8 md:mb-12">Projetos</h2>
      <p className="text-lg mb-2 text-center">Veja os trabalhos em desenvolvimento!</p>
      <div className="container mx-auto flex flex-wrap justify-center gap-8">
        {projetos.map((project) => (
          <div 
            key={project.id}
            className="card" 
            style={{ backgroundImage: `url(${project.image})` }}
            onClick={() => setSelectedProject(project)}
            onKeyDown={(e) => e.key === 'Enter' && setSelectedProject(project)}
            tabIndex={0}
            role="button"
          >
            <p className="card-text">{project.title}</p>
          </div>
        ))}
      </div>

      {selectedProject && (
        <div
            className="modal-overlay"
            role="button"
            tabIndex={0}
            aria-label="Fechar modal"
            onClick={() => setSelectedProject(null)}
            onKeyDown={(e) => (e.key === 'Enter' || e.key === ' ') && setSelectedProject(null)}
        >
            <div
                className="modal-content"
                role="dialog"
                aria-modal="true"
                tabIndex={0}
                onClick={(e) => e.stopPropagation()}
            >
                <div className="modal-header">
                    <h3 className="modal-title">{selectedProject.title}</h3>
                    <button className="close-button" onClick={() => setSelectedProject(null)}>×</button>
                </div>
                <div className="modal-body">
                    <p className="modal-description">{selectedProject.description}</p>
                    
                    {selectedProject.technologies && selectedProject.technologies.length > 0 && (
                        <div className="modal-technologies">
                            <h4>Tecnologias:</h4>
                            <ul className="tech-list">
                                {selectedProject.technologies.map((tech) => (
                                    <li key={tech} className="tech-item">{tech}</li>
                                ))}
                            </ul>
                        </div>
                    )}
                    
                    <p>
                        <strong>Status:</strong> 
                        <span className={`modal-status status-${selectedProject.status.toLowerCase().replace(' ', '-')}`}>
                            {selectedProject.status}
                        </span>
                    </p>
                </div>
            </div>
        </div>
      )}
    </div>
  );
}

// src/lib/sections/Projetos/Projetos.svelte
<script lang="ts">
    import './Projetos.css'
    import {projects, openModal, showModal, closeModal, selectedProject} from './Projetos'
    import { pageTitle } from '../../../stores';
    
    pageTitle.set('PET - Informática');
    
    
</script>

<svelte:head>
  <title>{$pageTitle}</title>
</svelte:head>

<div class="projects-section">
    <h2 class="text-3xl md:text-4xl font-bold text-center mb-8 md:mb-12">Projetos</h2>
    <p class="text-lg mb-2">Veja os trabalhos em desenvolvimento!</p>
    <div class="container">
        {#each projects as project}
            <div 
                class="card" 
                style="background-image: url('{project.image}')"
                on:click={() => openModal(project)}
                on:keydown={(e) => e.key === 'Enter' && openModal(project)}
                tabindex="0"
                role="button"
            >
                <p class="card-text">{project.title}</p>
            </div>
        {/each}
    </div>
</div>

<!-- Modal -->
{#if $showModal && $selectedProject}
    <div
        class="modal-overlay"
        role="button"
        tabindex="0"
        aria-label="Fechar modal"
        on:click={closeModal}
        on:keydown={(e) => (e.key === 'Enter' || e.key === ' ') && closeModal()}
    >
        <div
            class="modal-content"
            role="dialog"
            aria-modal="true"
            tabindex="0"
            on:click|stopPropagation
            on:keydown={(e) => e.stopPropagation()}
        >
            <div class="modal-header">
                <h3 class="modal-title">{$selectedProject.title}</h3>
                <button class="close-button" on:click={closeModal}>×</button>
            </div>
            <div class="modal-body">
                <p class="modal-description">{$selectedProject.description}</p>
                
                {#if $selectedProject.technologies && $selectedProject.technologies.length > 0}
                    <div class="modal-technologies">
                        <h4>Tecnologias:</h4>
                        <ul class="tech-list">
                            {#each $selectedProject.technologies as tech}
                                <li class="tech-item">{tech}</li>
                            {/each}
                        </ul>
                    </div>
                {/if}
                
                <p>
                    <strong>Status:</strong> 
                    <span class="modal-status status-{$selectedProject.status.toLowerCase().replace(' ', '-')}">
                        {$selectedProject.status}
                    </span>
                </p>
            </div>
        </div>
    </div>
{/if}
