// src/lib/sections/Inicio/Inicio.svelte
<script>
  import './Inicio.css'
  import { base } from '$app/paths';  
  import { pageTitle } from '../../../stores';
  pageTitle.set('PET - Informática');
</script>

<svelte:head>
  <title>{$pageTitle}</title>
</svelte:head>

<div class="banner" style="background-image: url({base}/pet_sala.png)">
  <h2>Desde 1991 realizando projetos inovadores!</h2>
</div>

// components/sections/Inicio.tsx
import React from 'react';
import styles from './Inicio.module.css';

export default function Inicio() {
  return (
    <>
      <div className={styles.banner} style={{ backgroundImage: "url(/fotos_sala/pet_sala.png)" }}>
        <h2>Desde 1991 realizando projetos inovadores!</h2>
      </div>
    </>
  );
}
